# Generated by Django 2.0.5 on 2018-06-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180609_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Album'),
        ),
    ]
